apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    service: {{ template "redis.name" . }}