apiVersion: v1
kind: Secret
metadata:
  name: {{ template "talk.fullname" . }}
type: "Opaque"
data:
{{- with .Values.talk.facebook }}
  facebookAppId: {{ .appId | b64enc | quote }}
  facebookAppSecret: {{ .appSecret | b64enc | quote }}
{{- end }}
{{- with .Values.talk.jwt }}
  jwtSecret: {{ .secret | b64enc | quote }}
  jwtAlg: {{ .alg | b64enc | quote }}
  jwtIssuer: {{ .issuer | b64enc | quote }}
  jwtCookieName: {{ .cookieName | b64enc | quote }}
{{- end }}
{{- with .Values.talk.smtp }}
  smtpFromAddress: {{ .fromAddress | b64enc | quote }}
  smtpHost: {{ .host | b64enc | quote }}
  smtpPassword: {{ .password | b64enc | quote }}
  smtpPort: {{ .port | b64enc | quote }}
  smtpUsername: {{ .username | b64enc | quote }}
{{- end }}