apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "talk.fullname" . }}
  name: {{ template "talk.fullname" . }}
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: {{ template "talk.fullname" . }}